# Generated by Django 2.2.7 on 2019-11-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movie_genres', to='movies.Genre'),
        ),
    ]
